---
title: "hrp_taphonomy"
author: "Jyhreh Johnson"
date: "2023-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Preliminaries
```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(jsonlite)
library(ggstatsplot)
```

#Load/Reload Data from PaleoCore
```{r}
hadar_df <- as.data.frame(fromJSON("https://paleocore.org/origins/api/hadarfossilelements/")) #loads in the Hadar fossil elements from paleocore. Make sure to save changes in paleocore before running. 
```

#Load Skeletal Element API
```{r}
hadar_api <- as.data.frame(fromJSON("https://paleocore.org/origins/api/skeletalelements/")) #loads in the skeletal element api in paleocore.
```

#Write df as csv
```{r}
write.csv(hadar_df,"C:\\Users\\JyhrehJohnson\\iCloudDrive\\Documents\\Documents\\UT\\masters_thesis\\hadar_df.csv", row.names=FALSE) #write the Hadar data as a csv file to save on computer and load into a spreadsheet. 

write.csv(hadar_api,"C:\\Users\\JyhrehJohnson\\iCloudDrive\\Documents\\Documents\\UT\\masters_thesis\\hadar_api.csv", row.names=FALSE) #write the Hadar api as a csv file to save on computer and load into a spreadsheet.
```

#Data Merge
```{r}
#When api is pulled, Denné gets 526 fossil specimens comprised of 811 unique skeletal elements
hadar_api1 <- as.data.frame(hadar_api[,-c(1)]) #remove id from original api data frame

#Check for duplicates
duplicated(hadar_api1$uberon_id)
hadar_api1[duplicated(hadar_api1$uberon_id),]

hadar_merge <- merge(hadar_df, hadar_api1, by.x="uberon_id", by.y = "uberon_id", all.x = FALSE, all.y = FALSE) #inner join the hadar df and api data frames
hadar_merge <- select(hadar_merge,"id", "fossil","name","uberon_id", "anatomical_region.y","completeness") #reorder columns

setdiff(hadar_df$id, hadar_merge$id) #find missing data


#hadar_df1 <- as.data.frame(hadar_df[,-c(1,5,6,8)]) #remove id,side,dental,preserved part from original hadar data frame #Deleted because keeping the ID is important 
#hadar_merge <- merge(hadar_df1, hadar_api1,by.x = "uberon_id", by.y = "uberon_id", all.x = FALSE,all.y = FALSE) 
```

#Bivariate Barplot/Expected v. Observed
```{r}
#identify proportions & counts; cranial, dental, axial, appendicular
skeleton.proportions <- c(22/206, 32/206, 26/206, 126/206) #proportions of regions
expected_count <- c(165, 98, 80, 385) #expected regional counts, calculations in Google Drive/Sheets under "Analysis"
hd_count <- c(114, 357, 68, 189) #observed hadar counts

#Bivariate Data
count_data <- data.frame(expected_count, hd_count) #create data frame with both counts
regions <- c("cranial", "dental", "axial", "appendicular") #add a regions column
count_data <- cbind(count_data, regions) #combind the count & regions
count_data <- select(count_data,"regions", "expected_count", "hd_count") #reorder
#count_data <- data.frame(t(count_data))

#Graph Dotchart
dotchart(count_data$hd_count, labels = count_data$regions, bg = "darkorange",
         pt.cex = 1.5, xlim = range(count_data$expected_count, count_data$hd_count) + c(-2, 2))
points(count_data$expected_count, 1:nrow(count_data), col = "black", pch = 19, cex = 1.5)

#Barplot
#biv_plot <- ggplot(count_data, aes(x=hd_count, y=expected_count, fill = regions)) + 
 # geom_bar(stat= "identity", position = "dodge") #create barplot
#biv_plot 
```

#BarStackPlot/For Fragmentation [USE]
```{r}
#UPDATE 
hd_chisq <- na.omit(hadar_merge[,c("anatomical_region.y", "completeness")]) #gives 729 elements 
hd_chisq2 <- hadar_merge[,c("anatomical_region.y", "completeness")]
#without na.omit gives 808 elements

sum(is.na(hd_chisq)) #count the number of NAs = 0 NAs /729 elements
sum(is.na(hd_chisq2)) #count the number of NAs = 80 NAs /728 elements
#basically the same thing so will get 729 observations like before

chisq_plot <- ggbarstats(data = hd_chisq, x = completeness, y = anatomical_region.y) + labs(caption=NULL) #show the preservation stats for each anatomical region
chisq_plot #prints the stacked plots per anatomical region

#Density Plot
#curve(dchisq(x, df = 4), from = 0, to = 15, main = "Chi-Square Distribution (df = 4)", ylab = 'Density', lwd = 2, col = 'orange')
```

#Completeness Distrubtion [Use for completeness count]
```{r}
comp <- table(hadar_merge$completeness)
comp_df <- as.data.frame(comp)
```

#Uberon Count
```{r}
uberon_count <- table(hadar_merge$name, hadar_merge$uberon_id)
uberon_count_df <- as.data.frame(uberon_count)
uberon_count_df <- uberon_count_df[-1,]
```

#Element Count
```{r}
element <- table(hadar_merge$name, hadar_merge$uberon_id)
element_df <- as.data.frame(element)
```
